version: 2.1

commands:
  trigger-pipeline-fail-notification:
    steps:
      - run:
          name: Trigger a notification on failed pipeline when a PR is open
          command: |
            curl --request POST \
              --url https://circleci.com/api/v2/project/gh/jenny-miggin/config-repo/pipeline/run \
              --header "Circle-Token: $CIRCLECI_API_TOKEN" \
              --header 'content-type: application/json' \
              --data '{"definition_id":"6867b583-4021-4635-b37a-cc62e88b8763","config":{"branch":"main"},"checkout":{"branch":"main"},"parameters":{"COMMIT_SHA":"$CIRCLE_SHA1"}}' 

jobs:
  my-tests:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: My Test Suite
          command: |
            echo "tests are running"
            exit 1
  trigger-notification:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - trigger-pipeline-fail-notification

workflows:
  build-and-test:
    jobs:
      - my-tests
      - trigger-notification:
          requires:
            - my-tests:
                - failed
          context: cci