version: 2.1

commands:
  trigger-pipeline-fail-notification:
    steps:
      - run:
          name: Trigger a webhook on failed pipeline when a PR is open
          command: |
            curl -X POST -H "content-type: application/json" 'https://internal.circleci.com/private/soc/e/b33ea326-fd7e-49b1-a6bb-04bb5eb12813?secret=${WEBHOOK_SECRET}

jobs:
  my-tests:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: My Test Suite
          command: |
            echo "tests are running and are going to fail"
            exit 1

  trigger-notification:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - trigger-pipeline-fail-notification

workflows:
  build-and-test:
    jobs:
      - my-tests
      - trigger-notification:
          requires:
            - my-tests:
                - failed
          context: cci